Use aiida tag 1.3.0, temporarily remove BigDFT
marvel-nccr/ansible-playbook-workhorse pull request #18
Opened 2020-07-01 17:54 UTC by borellim

2020-07-01 17:58 UTC, chrisjsewell requested changes

2020-07-01 17:58 UTC, chrisjsewell commented on playbook.yml
> +    #- role: marvel-nccr.bigdft
```suggestion
    # this can be added back when ansible-role-bigdft/issues/8 is fixed
    #- role: marvel-nccr.bigdft
```

2020-07-02 17:18 UTC, chrisjsewell approved these changes

2020-07-02 17:20 UTC, merged

2020-07-02 22:18 UTC, borellim commented
Thanks Chris.